### ISSUE TITLE
Is it a known issue that 'pip install intake' is missing required dependencies?

### ISSUE THREAD

**Issue by danielballan** [ContinuumIO/intake#266]
Is it a known issue that 'pip install intake' is missing required dependencies? It might be worth rolling a bugfix release soon to ensure that `pyyaml` gets installed with intake.

Here's an example installation of 0.4.1 into a clean venv:

```bash
08:25 $ python -m venv ~/venv/test-intake-install
08:26 $ source ~/venv/test-intake-install/bin/activate
08:26 $ pip install wheel
<snipped>
Installing collected packages: wheel
Successfully installed wheel-0.33.0
08:26 $ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
pip (9.0.1)
pkg-resources (0.0.0)
setuptools (39.0.1)
wheel (0.33.0)
08:26 $ pip install "intake==0.4.1"
Collecting intake==0.4.1
<snipped>
Installing collected packages: appdirs, dask, param, pyviz-comms, numpy, holoviews, MarkupSafe, jinja2, msgpack, msgpack-numpy, msgpack-python, pytz, six, python-dateutil, pandas, python-snappy, chardet, certifi, urllib3, idna, requests, ruamel.yaml, tornado, intake
Successfully installed MarkupSafe-1.1.0 appdirs-1.4.3 certifi-2018.11.29 chardet-3.0.4 dask-1.1.1 holoviews-1.11.2 idna-2.8 intake-0.4.1 jinja2-2.10 msgpack-0.6.1 msgpack-numpy-0.4.4.2 msgpack-python-0.5.6 numpy-1.16.1 pandas-0.24.1 param-1.8.2 python-dateutil-2.8.0 python-snappy-0.5.3 pytz-2018.9 pyviz-comms-0.7.0 requests-2.21.0 ruamel.yaml-0.15.87 six-1.12.0 tornado-5.1.1 urllib3-1.24.1
08:26 $ python -c "import intake"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dallan/venv/test-intake-install/lib/python3.6/site-packages/intake/__init__.py", line 16, in <module>
    from .source.base import Schema, DataSource
  File "/home/dallan/venv/test-intake-install/lib/python3.6/site-packages/intake/source/base.py", line 11, in <module>
    from .cache import make_caches
  File "/home/dallan/venv/test-intake-install/lib/python3.6/site-packages/intake/source/cache.py", line 19, in <module>
    from dask.bytes.utils import infer_storage_options
  File "/home/dallan/venv/test-intake-install/lib/python3.6/site-packages/dask/bytes/__init__.py", line 4, in <module>
    from .core import read_bytes, open_files
  File "/home/dallan/venv/test-intake-install/lib/python3.6/site-packages/dask/bytes/core.py", line 9, in <module>
    from toolz import merge
ModuleNotFoundError: No module named 'toolz'
08:26 $ pip install dask[bag]
Requirement already satisfied: dask[bag] in /home/dallan/venv/test-intake-install/lib/python3.6/site-packages
Collecting toolz>=0.7.3; extra == "bag" (from dask[bag])
Collecting partd>=0.3.8; extra == "bag" (from dask[bag])
  Using cached https://files.pythonhosted.org/packages/e2/bc/4dfd1e62e04a26d7ee56ade63af15e3249aeb3ed05d70ac590da2ca7c44d/partd-0.3.9-py2.py3-none-any.whl
Collecting cloudpickle>=0.2.1; extra == "bag" (from dask[bag])
  Using cached https://files.pythonhosted.org/packages/34/80/66d06012248d7a8d3caf8c52937d435371336fb1161eb919ff6a57dccc70/cloudpickle-0.7.0-py2.py3-none-any.whl
Collecting locket (from partd>=0.3.8; extra == "bag"->dask[bag])
Installing collected packages: toolz, locket, partd, cloudpickle
Successfully installed cloudpickle-0.7.0 locket-0.2.0 partd-0.3.9 toolz-0.9.0
08:26 $ python -c "import intake"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dallan/venv/test-intake-install/lib/python3.6/site-packages/intake/__init__.py", line 16, in <module>
    from .source.base import Schema, DataSource
  File "/home/dallan/venv/test-intake-install/lib/python3.6/site-packages/intake/source/base.py", line 11, in <module>
    from .cache import make_caches
  File "/home/dallan/venv/test-intake-install/lib/python3.6/site-packages/intake/source/cache.py", line 20, in <module>
    from intake.config import conf
  File "/home/dallan/venv/test-intake-install/lib/python3.6/site-packages/intake/config.py", line 12, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
08:26 $ pip install pyyaml
Collecting pyyaml
Installing collected packages: pyyaml
Successfully installed pyyaml-3.13
08:31 $ python -c "import intake"  # success
```

**Comment by martindurant** [comment]
Should work after https://github.com/ContinuumIO/intake/pull/249

**Comment by danielballan** [comment]
Oh, makes sense. I even commented on that issue...sorry for the noise.

**Comment by jsignell** [comment]
Just to note that I was still missing snappy when installing with pip.

**Comment by martindurant** [comment]
@jsignell , feel free to PR for requirements for pip and/or conda

**Comment by jsignell** [comment]
I don't think there is a solution. python-snappy has an external dependency on the non-pip-installable snappy (https://github.com/andrix/python-snappy#dependencies). So it'll work fine if you conda install, but you'll be missing the real snappy if you pip install. This is the same as graphviz for instance.

**Comment by martindurant** [comment]
Oh, I see what you mean. We could have more detailed install instructions. Is snappy actually required for import?

**Comment by jsignell** [comment]
I am not sure. I ran into the issue when running tests.

**Comment by martindurant** [comment]
OK - it's one of the allowed serialisers, but not called by default. Not worried about this, then.
