### ISSUE TITLE
intake discover csv fails with Subclass should implement _get_schema()

### ISSUE THREAD

**Issue by ah-** [ContinuumIO/intake#70]
Running `intake discover` on the csv example fails with:

```
$ intake discover http://localhost:5000 example
Traceback (most recent call last):
  File "/opt/conda/bin/intake", line 6, in <module>
    exit(main())
  File "/opt/conda/lib/python3.6/site-packages/intake/cli/client/__main__.py", line 114, in main
    retcode = args.func(args)
  File "/opt/conda/lib/python3.6/site-packages/intake/cli/client/__main__.py", line 44, in discover
    with catalog[args.name].get() as f:
  File "/opt/conda/lib/python3.6/site-packages/intake/source/base.py", line 146, in __enter__
    self._load_metadata()
  File "/opt/conda/lib/python3.6/site-packages/intake/source/base.py", line 86, in _load_metadata
    self._schema = self._get_schema()
  File "/opt/conda/lib/python3.6/site-packages/intake/source/base.py", line 67, in _get_schema
    raise Exception('Subclass should implement _get_schema()')
Exception: Subclass should implement _get_schema()
```

Let me know if it's too early to be reporting these.

**Comment by martindurant** [comment]
These reports are useful, thank you.

**Comment by martindurant** [comment]
@seibert , what is the intended usage here? The CSV plugin does implement `_get_schema()`.

@ah- , the CSV plugin is the most basic one we could think of, and the only one included in Intake, in order to make some examples possible. It may be replaced by a more thorough `intake-csv` at some point.
